### ISSUE TITLE
Fixed: Error 403 on person

### ISSUE THREAD

**Issue by ik2wxx** [hacf-fr/renault-api#181]
Is anyone experiencing error 403 ?
Today I'm getting this error:
`aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/persons/86523cf5-aa91-4bfd-b76e-0f744e1ccf31?country=IT')
`Thank you
Roberto

**Comment by epenet** [comment]
Hi,

It was reported on https://github.com/hacf-fr/hassRenaultZE/issues/120, but I don't have a root cause for it yet.
I suspect something changed on the Renault servers, but the app seems to still work OK.

Also, it affects all endpoints, not just `persons` endpoint

**Comment by db-EV** [comment]
According to [@dehsgr](https://gist.github.com/dehsgr/32c4d3dd5f8125be3a4c66d04e41d9b8/revisions) are new API keys needed but his one doesn't work for my swedish account.

**Comment by epenet** [comment]
Thanks @db-EV 
The new key works for me - I've created corresponding PR #182 

@ik2wxx does that branch work for you?
@dehsgr how did you discover the new key? (you can email me at `dev_at_zeflip_com`)

**Comment by PysX** [comment]
PR works for me too, thanks!

**Comment by epenet** [comment]
Before I merge, I would like to know how to make it work for @db-EV 
Is it specific to countries? to models?
Is it possible to "request" the new API key from a server?
etc.

**Comment by db-EV** [comment]
It's working for me now as well. You can go ahead.
I don't know why it didn't work at the first try.

**Comment by mfonville** [comment]
When I decompiled the app it still has the old values in it. So I am quite sure they deploy the new values using Firebase remote-config: https://firebase.google.com/docs/remote-config

A test to check this would be to install the official app on an android device without Google Play Services (e.g. a LineageOS custom ROM and not installing any GApps) and to see if the app gets the updated key or not (I suspect not: because Firebase depends on Google Play Services).

Afaik there is no method (yet) to eavesdrop on the Firebase/Google connection. Though you could try to check the contents of the local configuration SQLite database of the app.

**Comment by epenet** [comment]
Yes, I was able to retrieve a sample from Firebase here: https://github.com/hacf-fr/renault-api/pull/184
